// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'we can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhiD0W6mzaYME-ZFG0ot40eBLWOD0BSVU',
    appId: '1:929226034837:web:7914c85e998fc0c0c4159c',
    messagingSenderId: '929226034837',
    projectId: 'vulnera-e8848',
    authDomain: 'vulnera-e8848.firebaseapp.com',
    storageBucket: 'vulnera-e8848.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD01KIjkE7wG_zOyOAz3XhpDL4bzdfWrUQ',
    appId: '1:929226034837:android:89a4d35f32f4e8d2c4159c',
    messagingSenderId: '929226034837',
    projectId: 'vulnera-e8848',
    storageBucket: 'vulnera-e8848.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmyU3kKoU4_RK8EgxixMP07IdC6KNGbRs',
    appId: '1:929226034837:ios:635eeab428bb9744c4159c',
    messagingSenderId: '929226034837',
    projectId: 'vulnera-e8848',
    storageBucket: 'vulnera-e8848.firebasestorage.app',
    iosBundleId: 'com.vulnera.vulnera',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmyU3kKoU4_RK8EgxixMP07IdC6KNGbRs',
    appId: '1:929226034837:ios:635eeab428bb9744c4159c',
    messagingSenderId: '929226034837',
    projectId: 'vulnera-e8848',
    storageBucket: 'vulnera-e8848.firebasestorage.app',
    iosBundleId: 'com.vulnera.vulnera',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhiD0W6mzaYME-ZFG0ot40eBLWOD0BSVU',
    appId: '1:929226034837:web:31f8b298f2349737c4159c',
    messagingSenderId: '929226034837',
    projectId: 'vulnera-e8848',
    authDomain: 'vulnera-e8848.firebaseapp.com',
    storageBucket: 'vulnera-e8848.firebasestorage.app',
  );
}
